site:
  title: Rancher product documentation
  start_page: latest@rancher-manager:en:about-rancher/what-is-rancher.adoc
  url: https://documentation.suse.com/cloudnative

content:
  sources:
    - url: ../fleet-product-docs # en
      branches: [main]
      start_paths: [versions/v0.12, versions/v0.11, versions/v0.10, versions/v0.9]
    - url: ../neuvector-product-docs # en
      branches: [main]
      start_paths: [docs/*]
    - url: ../elemental-product-docs # en
      branches: [main]
      start_paths: [docs/*]
    - url: ../turtles-product-docs # en
      branches: [main]
      start_paths: [versions/latest, versions/v0.24, versions/v0.23, versions/v0.22, versions/v0.21, versions/v0.20, versions/v0.19, versions/v0.18, versions/v0.17, versions/v0.16, versions/v0.15, versions/v0.14, versions/v0.13, versions/v0.12, versions/v0.11]
    - url: ../kubewarden-product-docs # en
      branches: [HEAD]
      start_paths: [shared, docs/version-*]
    - url: ../stackstate-product-docs # en
      branches: [HEAD]
      start_paths: [shared, docs/latest, docs/version-*]
    - url: ../longhorn-product-docs # en
      branches: [main]
      start_paths: [shared, docs/version-1.8, docs/version-1.9, docs/version-1.10]
    - url: ../harvester-product-docs # en
      branches: [main]
      start_paths: [versions/v1.6, versions/v1.5, versions/v1.4, versions/v1.3]
    - url: ../rancher-product-docs # en, zh
      start_paths: [shared, versions/latest, versions/v2.12, versions/v2.11, versions/v2.10, versions/v2.9, versions/v2.8]
    - url: ../rke2-product-docs # en, zh
      branches: [main]
      start_path: versions/latest
    - url: ../k3s-product-docs # en, ja, ko, zh
      branches: [main]
      start_path: versions/latest
ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ../../doc-suse-com/dsc-style-bundle/supplemental-files/rancher

asciidoc:
  attributes:
    page-pagination: ''
    tabs-sync-option: ''
    kw-build-type: 'product' # One of 'community' or 'product'
    kw-product-name: 'SUSE® Rancher Prime: Admission Policy Manager (Kubewarden)'
    kw-community-name: 'Kubewarden'
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en, ja, zh] # ko not supported by extension
    index_latest_only: true
  - require: '@sntke/antora-mermaid-extension' # <1>
    mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
    script_stem: header-scripts # <3>
    mermaid_initialize_options: # <4>

output:
  dir: build/site
