site:
  title: Rancher product documentation
  start_page: latest@rancher-manager:en:about-rancher/what-is-rancher.adoc
  url: https://documentation.suse.com/cloudnative

content:
  sources:
    - url: ../fleet-product-docs # en
      branches: [main]
      start_paths: [versions/v0.10, versions/v0.9]
    - url: ../neuvector-product-docs # en
      branches: [main]
      start_paths: [docs/*]
    - url: ../elemental-product-docs # en
      branches: [main]
      start_paths: [docs/*]
    - url: ../turtles-product-docs # en
      branches: [main]
      start_paths: [versions/v0.13, versions/v0.12, versions/v0.11]
    - url: ../kubewarden-product-docs # en
      branches: [main]
      start_paths: [shared, docs/next, docs/version-1.16, docs/version-1.17, docs/version-1.18, docs/version-1.19, docs/version-1.20]
    - url: ../longhorn-product-docs # en
      branches: [main]
      start_paths: [shared, docs/version-1.7.0]
    - url: ../harvester-product-docs # en
      branches: [main]
      start_paths: [versions/v1.3, versions/v1.4]
    - url: ../rancher-product-docs # en, zh
      start_paths: [shared, versions/latest, versions/v2.10, versions/v2.9, versions/v2.8]
    - url: ../rke2-product-docs # en, zh
      branches: [main]
      start_path: versions/latest 
    - url: ../k3s-product-docs # en, ja, ko, zh
      branches: [main]
      start_path: versions/latest
ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files

asciidoc:
  attributes:
    page-pagination: ''
    tabs-sync-option: ''
    kw-build-type: 'product' # One of 'community' or 'product'
    kw-product-name: 'SUSE® Rancher Prime: Admission Policy Manager (Kubewarden)'
    kw-community-name: 'Kubewarden'
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en, ja, zh] # ko not supported by extension
  - require: '@sntke/antora-mermaid-extension' # <1>
    mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
    script_stem: header-scripts # <3>
    mermaid_initialize_options: # <4>

output:
  dir: build/site
