name: Rancher product documentation - publish to GitHub Pages with Lunr Search Extension
on:
  # Runs every hour.
  schedule:
    - cron: '20 * * * *'
  # Runs whenever a change is pushed to the main branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  group: github-pages
  cancel-in-progress: false
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure Pages
        uses: actions/configure-pages@v3
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Antora with the Antora Lunr Extension
        run: make environment
      - name: Generate Site
        run: make remote
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/site
      - name: Push the static site content to gh-pages branch
        env:
          ACTOR: ${{ github.event_name == 'schedule' && 'github-actions[bot]' || github.actor }}
          ACTOR_EMAIL: ${{ github.event_name == 'schedule' && '41898282+github-actions[bot]' || github.actor }}
          COMMIT_MESSAGE: ${{ github.event_name == 'schedule' && '[scheduled] Deploy to gh-pages branch' || 'Deploy to gh-pages branch' }}
        run: |
          git config --global user.name "${ACTOR}"
          git config --global user.email "${ACTOR_EMAIL}@users.noreply.github.com"
          mv build/site ../site-temp
          git checkout --orphan gh-pages
          git rm -rf .
          rm -rf node_modules tmp
          mv ../site-temp/* .
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push --force origin gh-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
